### PR TITLE
Integration with Codecov.io

### PR DESCRIPTION
**Pull request by oartyshko**

### CODE REVIEW

**Comment by disist** [comment]
Could you please add badge to readme.md

**Comment by kucherenko** [comment]
are we going to add this for backend?

**Comment by oartyshko** [comment]
@kucherenko  coverage report is already added for BE, but not codecov. I think it should be changed to codecov. I can do it.

**Comment by disist** [comment]
Looks fine

**Comment by antonSavk** [comment]
+1

**Comment by yurii-sorokin** [comment]
+1

**Pull request merged**
